### ISSUE TITLE
Feature Request: Add support for more than one file

### ISSUE THREAD

**Issue by vu-truong** [SimplGy/obsidian-open-file-by-magic-date#3]
This plugin solved my problem. 
Thank you for creating it.

Currently it supports only one file. But I have many files based on date such as working daily note, learning daily note, etc.
And I want to assign a hotkey for each of those. For example, "Alt+L" for "Learning daily note" and "Alt+W" for working daily note.

Do you plan to add it in the future?

**Comment by SimplGy** [comment]
Should be possible to add multiple bindings up to some limit, would 10 be enough?

Not in my plans right now, but I'd review a PR that was manually tested and included screenshots. It's probably not the easiest because the setting menu needs to support adding and removing rows, but not that hard. Design would probably be to have a command entry for each file:

"Open file by magic date [1]"
"Open file by magic date [2]"
and so on.
